before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: l65DnMMBCUEgDkSsP/WcFgeHBobAaCVAFrxd/mpliVBow2+GGuyIusiHhOOCvUMA61xekHw4qEG2/zXEHMNNFZPe0JDxIJezdv0pL2wmY7jez7kCrjTHVjzuc05jUx6owz9vk1NskqRV+ezD/rLfh7Tyju1zjkdfhr6+OZDVBEHfPVefboWEB9G12ubKHJXeu8aTvc3BAfS0AfRjtr55diakWmsdAQ4ySIO530KbTuioWSFw7z+0/yfEb6e0F2oCLOtF9Il4O8Fn3ScdcD3UBXpVuzzf28+s5lM5FlNpqMRbGhG0zViSVXK1JG0g6XQ+MHjrdI6/iJ6Aic6O3CmOFd+veGVSII9hlJKbth0uD7cChPcTJbkO9FnMGLWJANhdekzO9JxT4g+g9675nuHCUqlB0S3DIkCOlxR9IRlHHA37GwH7i/Nfzj+1tAOTAdjzx9OqlcV49spJIsBcpSxUw5DdU9wRUsD25miMJrUrdpTKKwHM6WaLEorSwA0M69V8K71HxWK14HvICwu7Mu9TWOgFWht+7R7DV9+Ygpv/pgHaWx3YQ7/gIFWwJWgHlGzRcpgyUKgupurGAfeyJ5477S9a5Vj5ZQCEBBUkaz69/nf4w+5ih5dwJ/TBCD5UrzxuJ/FFHWN7bMjJ1hMMZQy+RUvnWbv1AF9xtLEk5R442Aw= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
